"""added user_id

Revision ID: 78bddc1ad1d4
Revises: cc7f89a12234
Create Date: 2025-03-25 15:24:21.551928

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '78bddc1ad1d4'
down_revision: Union[str, None] = 'cc7f89a12234'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feedback', sa.Column('user_id', sa.String(length=36), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('feedback', 'user_id')
    # ### end Alembic commands ###
