"""Staff_id and store_id added

Revision ID: 4d5c3a26d766
Revises: c524b921ba59
Create Date: 2025-03-27 21:58:05.066515

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4d5c3a26d766"
down_revision: Union[str, None] = "c524b921ba59"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "feedback", sa.Column("staff_id", sa.String(length=36), nullable=False)
    )
    op.add_column(
        "voice_recording", sa.Column("store_id", sa.String(length=36), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("voice_recording", "store_id")
    op.drop_column("feedback", "staff_id")
    # ### end Alembic commands ###
