"""removed staff_id

Revision ID: 8ecee3c85a66
Revises: 4d5c3a26d766
Create Date: 2025-03-27 23:27:52.637892

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "8ecee3c85a66"
down_revision: Union[str, None] = "4d5c3a26d766"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("feedback", "staff_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "feedback", sa.Column("staff_id", mysql.VARCHAR(length=36), nullable=False)
    )
    # ### end Alembic commands ###
