"""removed last_listening time

Revision ID: dd6d2629c9a8
Revises: 8ecee3c85a66
Create Date: 2025-03-29 18:15:18.984607

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'dd6d2629c9a8'
down_revision: Union[str, None] = '8ecee3c85a66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('voice_recording', 'last_listening_time')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('voice_recording', sa.Column('last_listening_time', mysql.DATETIME(), nullable=True))
    # ### end Alembic commands ###
