"""last_listning time changed and transcription_status added

Revision ID: cac839a2d9f5
Revises: dd6d2629c9a8
Create Date: 2025-03-29 18:16:18.776118

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cac839a2d9f5'
down_revision: Union[str, None] = 'dd6d2629c9a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('voice_recording', sa.Column('last_listening_time', sa.DateTime(), nullable=True))
    op.add_column('voice_recording', sa.Column('transcription_status', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('voice_recording', 'transcription_status')
    op.drop_column('voice_recording', 'last_listening_time')
    # ### end Alembic commands ###
