"""transcription enum added

Revision ID: 7942982cce8d
Revises: cac839a2d9f5
Create Date: 2025-04-08 12:13:25.201892

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '7942982cce8d'
down_revision: Union[str, None] = 'cac839a2d9f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('voice_recording', 'transcription_status',
               existing_type=mysql.ENUM('failed', 'pending', 'in_progress', 'completed'),
               type_=sa.Enum('failure', 'pending', 'in_progress', 'completed', name='transctriptionstatus'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('voice_recording', 'transcription_status',
               existing_type=sa.Enum('failure', 'pending', 'in_progress', 'completed', name='transctriptionstatus'),
               type_=mysql.ENUM('failed', 'pending', 'in_progress', 'completed'),
               existing_nullable=False)
    # ### end Alembic commands ###
