"""Trancribe ai table added

Revision ID: 7eb17be94ddc
Revises: 7942982cce8d
Create Date: 2025-04-08 19:58:42.594705

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7eb17be94ddc'
down_revision: Union[str, None] = '7942982cce8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transcribe_ai',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('audio_id', sa.String(length=36), nullable=False),
    sa.Column('gender', sa.String(length=255), nullable=True),
    sa.Column('language', sa.String(length=255), nullable=True),
    sa.Column('emotional_state', sa.JSON(), nullable=True),
    sa.Column('product_mentions', sa.JSON(), nullable=True),
    sa.Column('complaints', sa.JSON(), nullable=True),
    sa.Column('positive_keywords', sa.JSON(), nullable=True),
    sa.Column('negative_keywords', sa.JSON(), nullable=True),
    sa.Column('contact_reason', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transcribe_ai')
    # ### end Alembic commands ###
