"""created at added in transcribe_ai

Revision ID: 5e95e198ef93
Revises: 0c4b7158665c
Create Date: 2025-04-09 09:03:25.766467

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '5e95e198ef93'
down_revision: Union[str, None] = '0c4b7158665c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transcribe_ai', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('transcribe_ai', sa.Column('modified_at', sa.DateTime(), nullable=True))
    op.drop_column('transcribe_ai', 'contact_reason')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transcribe_ai', sa.Column('contact_reason', mysql.JSON(), nullable=True))
    op.drop_column('transcribe_ai', 'modified_at')
    op.drop_column('transcribe_ai', 'created_at')
    # ### end Alembic commands ###
