"""Initial migration

Revision ID: 9623f81ea301
Revises:
Create Date: 2025-03-12 20:49:20.606420

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9623f81ea301"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ai_analytics",
        sa.Column("AI_analytics_id", sa.String(length=36), nullable=False),
        sa.Column("transcription_id", sa.String(length=36), nullable=False),
        sa.Column("top_emotion", sa.String(length=255), nullable=False),
        sa.Column("frequent_complaint", sa.Text(), nullable=True),
        sa.Column("lead_interest", sa.Text(), nullable=True),
        sa.Column("csat_score", sa.Float(), nullable=True),
        sa.Column("usp", sa.Text(), nullable=True),
        sa.Column("objection_handling", sa.Text(), nullable=True),
        sa.Column("effectiveness", sa.Text(), nullable=True),
        sa.Column("targeted_feedback", sa.Text(), nullable=True),
        sa.Column("quality_assurance", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("modified_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("AI_analytics_id"),
    )
    op.create_table(
        "ml_analytics",
        sa.Column("ML_analytics_id", sa.String(length=36), nullable=False),
        sa.Column("transcription_id", sa.String(length=36), nullable=False),
        sa.Column("sentiment", sa.String(length=255), nullable=False),
        sa.Column("sentiment_score", sa.Float(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("modified_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("ML_analytics_id"),
    )
    op.create_table(
        "area",
        sa.Column("area_id", sa.String(length=36), nullable=False),
        sa.Column("area_name", sa.String(length=255), nullable=False),
        sa.Column("sales_id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("modified_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("area_id"),
    )
    op.create_table(
        "business",
        sa.Column("business_id", sa.String(length=36), nullable=False),
        sa.Column("business_name", sa.String(length=255), nullable=False),
        sa.Column(
            "business_status",
            sa.Enum("ACTIVE", "INACTIVE", "PENDING", "FAILURE", name="statusenum"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("modified_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("business_id"),
    )
    op.create_table(
        "store",
        sa.Column("store_id", sa.String(length=36), nullable=False),
        sa.Column("store_name", sa.String(length=255), nullable=False),
        sa.Column("store_code", sa.String(length=100), nullable=False),
        sa.Column("store_address", sa.Text(), nullable=False),
        sa.Column("district", sa.String(length=100), nullable=False),
        sa.Column("state", sa.String(length=100), nullable=False),
        sa.Column(
            "store_status",
            sa.Enum("ACTIVE", "INACTIVE", "PENDING", "FAILURE", name="statusenum"),
            nullable=False,
        ),
        sa.Column("business_id", sa.String(length=36), nullable=False),
        sa.Column("area_id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("modified_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("store_id"),
    )
    op.create_table(
        "user",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("role", sa.String(length=100), nullable=False),
        sa.Column("business_key", sa.String(length=255), nullable=False),
        sa.Column("store_id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("modified_at", sa.DateTime(), nullable=True),
        sa.Column(
            "user_status",
            sa.Enum("ACTIVE", "INACTIVE", "PENDING", "FAILURE", name="statusenum"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "voice_recording",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("audio_length", sa.Float(), nullable=False),
        sa.Column("transcription_id", sa.String(length=36), nullable=True),
        sa.Column("file_url", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("modified_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "transcription",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("transcription_text", sa.Text(), nullable=False),
        sa.Column("AI_analytics_id", sa.String(length=36), nullable=True),
        sa.Column("ML_analytics_id", sa.String(length=36), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("modified_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("transcription")
    op.drop_table("voice_recording")
    op.drop_table("user")
    op.drop_table("store")
    op.drop_table("business")
    op.drop_table("area")
    op.drop_table("ml_analytics")
    op.drop_table("ai_analytics")
    # ### end Alembic commands ###
