"""User table changes

Revision ID: 387ceb9229f4
Revises: 9623f81ea301
Create Date: 2025-03-13 17:49:24.036703

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "387ceb9229f4"
down_revision: Union[str, None] = "9623f81ea301"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("password", sa.String(length=256), nullable=False))
    op.add_column("user", sa.Column("email", sa.String(length=255), nullable=False))
    op.add_column(
        "user",
        sa.Column(
            "user_role",
            sa.Enum("L3", "L2", "L1", "L0", name="roleenum"),
            nullable=False,
        ),
    )
    op.drop_column("user", "role")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("role", mysql.VARCHAR(length=100), nullable=False))
    op.drop_column("user", "user_role")
    op.drop_column("user", "email")
    op.drop_column("user", "password")
    # ### end Alembic commands ###
