"""Voice recording datatable

Revision ID: fbfd619f4d20
Revises: 387ceb9229f4
Create Date: 2025-03-13 18:29:36.111771

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'fbfd619f4d20'
down_revision: Union[str, None] = '387ceb9229f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transcription', sa.Column('audio_id', sa.String(length=36), nullable=False))
    op.add_column('voice_recording', sa.Column('start_time', sa.DateTime(), nullable=False))
    op.add_column('voice_recording', sa.Column('end_time', sa.DateTime(), nullable=False))
    op.add_column('voice_recording', sa.Column('call_duration', sa.Float(), nullable=False))
    op.drop_column('voice_recording', 'transcription_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('voice_recording', sa.Column('transcription_id', mysql.VARCHAR(length=36), nullable=True))
    op.drop_column('voice_recording', 'call_duration')
    op.drop_column('voice_recording', 'end_time')
    op.drop_column('voice_recording', 'start_time')
    op.drop_column('transcription', 'audio_id')
    # ### end Alembic commands ###
