"""Staff table added

Revision ID: 7b5a3dc535b9
Revises: fbfd619f4d20
Create Date: 2025-03-14 20:25:35.306590

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '7b5a3dc535b9'
down_revision: Union[str, None] = 'fbfd619f4d20'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('staff',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email_id', sa.String(length=255), nullable=False),
    sa.Column('affilated_user_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.Column('staff_status', sa.Enum('ACTIVE', 'INACTIVE', 'PENDING', 'FAILURE', name='statusenum'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('user', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('user', 'modified_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.add_column('voice_recording', sa.Column('staff_id', sa.String(length=36), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('voice_recording', 'staff_id')
    op.alter_column('user', 'modified_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('user', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.drop_table('staff')
    # ### end Alembic commands ###
