"""Last login col added

Revision ID: 2ba5a01e0369
Revises: efcb04a0716e
Create Date: 2025-03-16 23:25:31.994069

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2ba5a01e0369"
down_revision: Union[str, None] = "efcb04a0716e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("last_login", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "last_login")
    # ### end Alembic commands ###
