"""area manager and role of state head added

Revision ID: 0521f88c7e26
Revises: 2ba5a01e0369
Create Date: 2025-03-19 20:06:29.510860

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0521f88c7e26"
down_revision: Union[str, None] = "2ba5a01e0369"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "area", sa.Column("area_manager_name", sa.String(length=255), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("area", "area_manager_name")
    # ### end Alembic commands ###
