"""last listening added

Revision ID: 3541a7482056
Revises: 2ba5a01e0369
Create Date: 2025-03-19 23:18:55.812673

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3541a7482056"
down_revision: Union[str, None] = "2ba5a01e0369"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "voice_recording", sa.Column("listening_time", sa.Float(), nullable=True)
    )
    op.add_column(
        "voice_recording",
        sa.Column("last_listening_time", sa.DateTime(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("voice_recording", "last_listening_time")
    op.drop_column("voice_recording", "listening_time")
    # ### end Alembic commands ###
