"""user role removed

Revision ID: 5250ff8eac4e
Revises: 3541a7482056
Create Date: 2025-03-20 19:51:47.338181

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "5250ff8eac4e"
down_revision: Union[str, None] = "3541a7482056"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "area", sa.Column("area_manager_name", sa.String(length=255), nullable=False)
    )
    op.add_column(
        "area", sa.Column("area_manager_ph_no", sa.String(length=255), nullable=True)
    )
    op.alter_column(
        "area", "area_name", existing_type=mysql.VARCHAR(length=255), nullable=True
    )
    op.add_column("store", sa.Column("pin_code", sa.String(length=255), nullable=False))
    op.add_column("store", sa.Column("lat", sa.String(length=255), nullable=False))
    op.add_column("store", sa.Column("long", sa.String(length=255), nullable=False))
    op.add_column(
        "store", sa.Column("store_ph_no", sa.String(length=255), nullable=False)
    )
    op.drop_column("user", "user_role")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user",
        sa.Column("user_role", mysql.ENUM("L3", "L2", "L1", "L0"), nullable=False),
    )
    op.drop_column("store", "store_ph_no")
    op.drop_column("store", "long")
    op.drop_column("store", "lat")
    op.drop_column("store", "pin_code")
    op.alter_column(
        "area", "area_name", existing_type=mysql.VARCHAR(length=255), nullable=False
    )
    op.drop_column("area", "area_manager_ph_no")
    op.drop_column("area", "area_manager_name")
    # ### end Alembic commands ###
