"""listening time and dateadded

Revision ID: 6924cedcbb97
Revises: 0521f88c7e26
Create Date: 2025-03-19 21:26:27.417209

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6924cedcbb97'
down_revision: Union[str, None] = '0521f88c7e26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('voice_recording', sa.Column('listening_time', sa.Float(), nullable=True))
    op.add_column('voice_recording', sa.Column('last_listening_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('voice_recording', 'last_listening_time')
    op.drop_column('voice_recording', 'listening_time')
    # ### end Alembic commands ###
