"""user role added

Revision ID: cc7f89a12234
Revises: 5250ff8eac4e
Create Date: 2025-03-20 19:54:22.764397

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "cc7f89a12234"
down_revision: Union[str, None] = "5250ff8eac4e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user",
        sa.Column(
            "user_role",
            sa.Enum("L4", "L3", "L2", "L1", "L0", name="roleenum"),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "user_role")
    # ### end Alembic commands ###
